services:
  - type: web
    name: chess-trainer-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python chess_trainer_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TRAINER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
